### ISSUE TITLE
Feature request: msdf :)

### ISSUE THREAD

**Issue by r-lyeh-archived** [tangrams/fontstash-es#19]
https://github.com/Chlumsky/msdfgen

**Comment by karimnaaji** [comment]
hey @r-lyeh, we're not going to maintain this library (we switched to using and maintain https://github.com/hjanetzek/alfons/tree/wip which has a better Harfbuzz integration so this is where MSDF usage might happen).

I've been really interested in this technique though and will definitely keep an eye on it.

**Comment by r-lyeh-archived** [comment]
aha thx. i'll take a look
