### ISSUE TITLE
Demo doesn't compile

### ISSUE THREAD

**Issue by benstadin** [tangrams/fontstash-es#6]
Hi,

This library looks pretty promising, but the demo is broken currently. There are a few errors which stop the demo from compiling, e.g. the calls to glfonsVertices() and glfonsRasterize() within the view controller do not match the provided API. 

Kind regards
Ben

**Comment by karimnaaji** [comment]
Hi @benstadin thanks for reporting this,

I'm going to fix this as soon as possible, the demo hasn't been updated since the integration of this library in this project https://github.com/tangrams/tangram-es, but I'll fix that and also make the example simpler :)

Thanks you!

**Comment by benstadin** [comment]
Great, thanks! It would be cool if the demo would also have defines to show how to use it without FreeType and Harfbuzz.

**Comment by karimnaaji** [comment]
Hey @benstadin ,

The example should be fixed on this [branch](https://github.com/tangrams/fontstash-es/tree/gl-backend). And the demo should also be much simpler to start with.

Let me know how that works.

**Comment by benstadin** [comment]
Delayed thanks ;). Looks good.

Btw, there is a leftover XCode project file in the root folder of the project which could be removed.

**Comment by karimnaaji** [comment]
I'm not sure to see about which XCode project you are talking about, are you sure that those files are not only visible on your local repository?

**Comment by benstadin** [comment]
Sorry, indeed. It was .gitignored lcoally.
